import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :inout, InoutWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Inout.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :inout, InoutWeb.Endpoint,
  url: [host: "inout-app-name.herokuapp.com", port: 443],
  adapter: Bandit.PhoenixAdapter,
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  render_errors: [
    formats: [html: InoutWeb.ErrorHTML, json: InoutWeb.ErrorJSON],
    layout: false
  ],
  pubsub_server: Inout.PubSub,
  live_view: [signing_salt: System.get_env("SIGNING_SALT") || "27fnTTwX"]
